services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: vytautasdev
      POSTGRES_PASSWORD: pass1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

# docker run --name customer-db-api --rm -p 8080:8080 --network  customer-database_postgres vytautasdev/customer-db-api --spring.datasource.url=jdbc:postgresql://db:5432/customer

# vytautasdev/customer-db-api == amigoscode/amigoscode-api
  customer-db-api:
    container_name: customer-db-api
    image: vytautasdev/customer-db-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: